[package]
name = "grepverse"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.17"
regex = "1.10.6"
rayon = "1.10.0"
walkdir = "2.5.0"
ansi_term = "0.12.1"
globset = "0.4.14"
memmap2 = "0.9.4"
atty = "0.2.14"

